"""add phases 7 to 10 world tools

Revision ID: 46da5e423370
Revises: 0010_master_rest
Create Date: 2026-07-27 16:52:10.625338
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46da5e423370'
down_revision: Union[str, None] = '0010_master_rest'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creatures',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('source_creature_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('hit_points', sa.Integer(), nullable=False),
    sa.Column('challenge_rating', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('encounter_weight', sa.Integer(), nullable=False),
    sa.Column('biomes', sa.JSON(), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('treasure', sa.JSON(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_creatures_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_creature_id'], ['creatures.id'], name=op.f('fk_creatures_source_creature_id_creatures')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creatures'))
    )
    op.create_index(op.f('ix_creatures_campaign_id'), 'creatures', ['campaign_id'], unique=False)
    op.create_table('dashboard_layouts',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('template_code', sa.String(length=40), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('cards', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility IN ('private', 'shared', 'presentation')", name=op.f('ck_dashboard_layouts_visibility_allowed')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_dashboard_layouts_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_dashboard_layouts_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_layouts'))
    )
    op.create_index(op.f('ix_dashboard_layouts_campaign_id'), 'dashboard_layouts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_dashboard_layouts_owner_user_id'), 'dashboard_layouts', ['owner_user_id'], unique=False)
    op.create_table('encounters',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('biome', sa.String(length=100), nullable=False),
    sa.Column('weather', sa.String(length=100), nullable=False),
    sa.Column('time_of_day', sa.String(length=40), nullable=False),
    sa.Column('danger', sa.Integer(), nullable=False),
    sa.Column('estimated_difficulty', sa.String(length=30), nullable=False),
    sa.Column('difficulty_is_estimate', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('creatures', sa.JSON(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'active', 'completed')", name=op.f('ck_encounters_status_allowed')),
    sa.CheckConstraint('danger BETWEEN 1 AND 5', name=op.f('ck_encounters_danger_range')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_encounters_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encounters'))
    )
    op.create_index(op.f('ix_encounters_campaign_id'), 'encounters', ['campaign_id'], unique=False)
    op.create_table('knowledge_nodes',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_knowledge_nodes_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_nodes'))
    )
    op.create_index(op.f('ix_knowledge_nodes_campaign_id'), 'knowledge_nodes', ['campaign_id'], unique=False)
    op.create_table('library_entries',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('source_entry_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('is_identified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('item', 'spell', 'condition', 'service')", name=op.f('ck_library_entries_kind_allowed')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_library_entries_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entry_id'], ['library_entries.id'], name=op.f('fk_library_entries_source_entry_id_library_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library_entries'))
    )
    op.create_index(op.f('ix_library_entries_campaign_id'), 'library_entries', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_library_entries_kind'), 'library_entries', ['kind'], unique=False)
    op.create_table('shops',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('owner_name', sa.String(length=160), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('opening_hours', sa.String(length=160), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_shops_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops'))
    )
    op.create_index(op.f('ix_shops_campaign_id'), 'shops', ['campaign_id'], unique=False)
    op.create_table('travel_plans',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('origin', sa.String(length=160), nullable=False),
    sa.Column('destination', sa.String(length=160), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pace', sa.String(length=30), nullable=False),
    sa.Column('difficult_terrain', sa.Boolean(), nullable=False),
    sa.Column('severe_weather', sa.Boolean(), nullable=False),
    sa.Column('hidden_fatigue_enabled', sa.Boolean(), nullable=False),
    sa.Column('traveler_ids', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_travel_plans_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_travel_plans'))
    )
    op.create_index(op.f('ix_travel_plans_campaign_id'), 'travel_plans', ['campaign_id'], unique=False)
    op.create_table('knowledge_edges',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=80), nullable=False),
    sa.Column('directed', sa.Boolean(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_knowledge_edges_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], name=op.f('fk_knowledge_edges_source_node_id_knowledge_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], name=op.f('fk_knowledge_edges_target_node_id_knowledge_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_edges'))
    )
    op.create_index(op.f('ix_knowledge_edges_campaign_id'), 'knowledge_edges', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_source_node_id'), 'knowledge_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_target_node_id'), 'knowledge_edges', ['target_node_id'], unique=False)
    op.create_table('shop_stock',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('library_entry_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_gp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_gp >= 0', name=op.f('ck_shop_stock_price_nonnegative')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_shop_stock_quantity_nonnegative')),
    sa.ForeignKeyConstraint(['library_entry_id'], ['library_entries.id'], name=op.f('fk_shop_stock_library_entry_id_library_entries')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shop_stock_shop_id_shops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_stock')),
    sa.UniqueConstraint('shop_id', 'library_entry_id', name=op.f('uq_shop_stock_shop_id'))
    )
    op.create_index(op.f('ix_shop_stock_library_entry_id'), 'shop_stock', ['library_entry_id'], unique=False)
    op.create_index(op.f('ix_shop_stock_shop_id'), 'shop_stock', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_stock_shop_id'), table_name='shop_stock')
    op.drop_index(op.f('ix_shop_stock_library_entry_id'), table_name='shop_stock')
    op.drop_table('shop_stock')
    op.drop_index(op.f('ix_knowledge_edges_target_node_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_source_node_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_campaign_id'), table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    op.drop_index(op.f('ix_travel_plans_campaign_id'), table_name='travel_plans')
    op.drop_table('travel_plans')
    op.drop_index(op.f('ix_shops_campaign_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_library_entries_kind'), table_name='library_entries')
    op.drop_index(op.f('ix_library_entries_campaign_id'), table_name='library_entries')
    op.drop_table('library_entries')
    op.drop_index(op.f('ix_knowledge_nodes_campaign_id'), table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    op.drop_index(op.f('ix_encounters_campaign_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_dashboard_layouts_owner_user_id'), table_name='dashboard_layouts')
    op.drop_index(op.f('ix_dashboard_layouts_campaign_id'), table_name='dashboard_layouts')
    op.drop_table('dashboard_layouts')
    op.drop_index(op.f('ix_creatures_campaign_id'), table_name='creatures')
    op.drop_table('creatures')
    # ### end Alembic commands ###
